[job-exec "monthly_credit_topup"]
schedule = "0 0 1 * *"
container = "credit"
command= "/credits-utils.sh topup"

[job-local "beat.twoweekly-restart"]
schedule = "0 0 0 */14 * *"
command = "/container-restart.sh beat" 

[job-local "worker.twoweekly-restart"]
schedule = "0 0 0 */14 * *"
command = "/container-restart.sh worker" 

[job-local "app.twoweekly-restart"]
schedule = "0 0 0 */14 * *"
command = "/container-restart.sh app" 